### PR TITLE
simplification of offset computation and volume curve estimation

### PR DESCRIPTION
**Pull request by NolwenHuet**

### CODE REVIEW

**Comment by NolwenHuet** [comment]
Hi Albert,
These modifications correspond to what we discuss previously by mail.

Best regards,
--
Nolwen

**Comment by albertcthomas** [comment]
Thanks @NolwenHuet ! this looks good. I will review the PR in the next few days. Sorry for the delay.

**Comment by albertcthomas** [comment]
Actually, when interested in specific minimum volume sets, one might want to have the offsets. I suggest adding a parameter `return_offsets`. If it is set to False (default) the function will only return the models, if it is set to True, the function will return both the models and the offsets. Otherwise LGTM. Sorry for the huge delay.

**Comment by albertcthomas** [comment]
I took over this PR and the fixes have been merged to master. Thanks @NolwenHuet!

**Pull request closed without merging**
